library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

library work;
use work.crossbar_pkg.all;

entity fp_addsub_wrapper is
    Port (
        aclk            : in std_logic;
        aresetn         : in std_logic;
        
        -- Input (AXI-Stream like)
        s_axis_valid    : in std_logic;
        s_axis_data     : in std_logic_vector(ADDSUB_DATA_WIDTH-1 downto 0);  -- 65 bits: two FP32 + op bit
        s_axis_tid      : in std_logic_vector(TID_WIDTH-1 downto 0);
        
        -- Output (AXI-Stream like)
        m_axis_valid    : out std_logic;
        m_axis_data     : out std_logic_vector(FP32_WIDTH-1 downto 0);        -- 32 bits: FP32 result
        m_axis_tid      : out std_logic_vector(TID_WIDTH-1 downto 0)
    );
end fp_addsub_wrapper;

architecture Behavioral of fp_addsub_wrapper is

    -- Xilinx FP Add/Subtract component (will be generated by IP)
    component floating_point_addsub
        port (
            aclk                : in std_logic;
            s_axis_a_tvalid     : in std_logic;
            s_axis_a_tdata      : in std_logic_vector(31 downto 0);
            s_axis_b_tvalid     : in std_logic;
            s_axis_b_tdata      : in std_logic_vector(31 downto 0);
            s_axis_operation_tvalid : in std_logic;
            s_axis_operation_tdata  : in std_logic_vector(7 downto 0);  -- operation: 0=add, 1=subtract
            m_axis_result_tvalid: out std_logic;
            m_axis_result_tdata : out std_logic_vector(31 downto 0)
        );
    end component;
    
    -- TID delay pipeline to match FP unit latency
    type tid_delay_array_t is array (0 to FP_LATENCY-1) of std_logic_vector(TID_WIDTH-1 downto 0);
    signal tid_delay : tid_delay_array_t := (others => (others => '0'));
    
    -- Valid delay pipeline
    type valid_delay_array_t is array (0 to FP_LATENCY-1) of std_logic;
    signal valid_delay : valid_delay_array_t := (others => '0');
    
    -- Split input data into two operands and operation bit
    signal operand_a : std_logic_vector(31 downto 0);
    signal operand_b : std_logic_vector(31 downto 0);
    signal operation_bit : std_logic;
    signal operation_data : std_logic_vector(7 downto 0);
    
    -- FP IP output
    signal fp_result_valid : std_logic;
    signal fp_result_data : std_logic_vector(31 downto 0);

begin

    -- Extract operands and operation from input data
    -- Assuming data format: [op_bit(64), operand_b(63:32), operand_a(31:0)]
    operand_a <= s_axis_data(31 downto 0);
    operand_b <= s_axis_data(63 downto 32);
    operation_bit <= s_axis_data(64);
    
    -- Convert operation bit to 8-bit format for IP
    -- 0 = add, 1 = subtract
    operation_data <= "00000000" when operation_bit = '0' else "00000001";
    
    -- Instantiate Xilinx FP Add/Subtract IP
    fp_addsub_inst : floating_point_addsub
        port map (
            aclk                    => aclk,
            s_axis_a_tvalid         => s_axis_valid,
            s_axis_a_tdata          => operand_a,
            s_axis_b_tvalid         => s_axis_valid,
            s_axis_b_tdata          => operand_b,
            s_axis_operation_tvalid => s_axis_valid,
            s_axis_operation_tdata  => operation_data,
            m_axis_result_tvalid    => fp_result_valid,
            m_axis_result_tdata     => fp_result_data
        );
    
    -- TID and valid delay pipeline to match FP unit latency
    process(aclk)
    begin
        if rising_edge(aclk) then
            if aresetn = '0' then
                tid_delay <= (others => (others => '0'));
                valid_delay <= (others => '0');
            else
                -- Shift TID through pipeline
                tid_delay(0) <= s_axis_tid;
                for i in 1 to FP_LATENCY-1 loop
                    tid_delay(i) <= tid_delay(i-1);
                end loop;
                
                -- Shift valid through pipeline
                valid_delay(0) <= s_axis_valid;
                for i in 1 to FP_LATENCY-1 loop
                    valid_delay(i) <= valid_delay(i-1);
                end loop;
            end if;
        end if;
    end process;
    
    -- Output assignments
    m_axis_valid <= fp_result_valid;
    m_axis_data <= fp_result_data;
    m_axis_tid <= tid_delay(FP_LATENCY-1);

end Behavioral;
